package models

import (
	"time"

	"github.com/google/uuid"
)

// Group is a named multi-party chat room stored in PostgreSQL. Its messages are
// end-to-end encrypted under a symmetric group key generated by the creator's
// client — the server only ever holds per-member wrapped copies of that key
// (see GroupMember.WrappedKey) and remains a blind router for group traffic.
type Group struct {
	GroupID   uuid.UUID `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"group_id"`
	Name      string    `gorm:"type:varchar(64);not null" json:"name"`
	CreatedBy uuid.UUID `gorm:"type:uuid;not null" json:"created_by"`
	CreatedAt time.Time `gorm:"autoCreateTime" json:"created_at"`
}

// TableName overrides the default GORM table name for the Group model.
func (Group) TableName() string {
	return "groups"
}

// Group member roles.
const (
	GroupRoleOwner  = "owner"
	GroupRoleMember = "member"
)

// GroupMember links a user to a group they belong to.
//
// WrappedKey/KeyNonce hold the group's AES key encrypted for this member under
// the pairwise ECDH key between the member and WrappedBy (the user whose client
// performed the wrap — the creator at group creation, or the inviter for a
// member who joined via invite). The member's client derives the same pairwise
// key from its own private key + WrappedBy's public key and unwraps locally;
// the server cannot recover the group key from what is stored here.
type GroupMember struct {
	GroupID    uuid.UUID `gorm:"type:uuid;primaryKey;not null" json:"group_id"`
	UserID     uuid.UUID `gorm:"type:uuid;primaryKey;not null" json:"user_id"`
	Role       string    `gorm:"type:varchar(16);not null;default:'member'" json:"role"`
	WrappedKey string    `gorm:"type:text;not null" json:"wrapped_key"`
	KeyNonce   string    `gorm:"type:text;not null" json:"key_nonce"`
	WrappedBy  uuid.UUID `gorm:"type:uuid;not null" json:"wrapped_by"`
	JoinedAt   time.Time `gorm:"autoCreateTime" json:"joined_at"`
}

// TableName overrides the default GORM table name for the GroupMember model.
func (GroupMember) TableName() string {
	return "group_members"
}

// Group invite lifecycle states.
const (
	InviteStatusPending  = "pending"
	InviteStatusAccepted = "accepted"
	InviteStatusDeclined = "declined"
)

// GroupInvite is a pending invitation for ToUser to join a group. The inviter's
// client wraps the group key for the invitee at invite time (it needs the
// invitee's public key, fetched like any peer's); on accept the wrapped key is
// copied onto the new GroupMember row so the invitee can unwrap it.
//
// One live invite per (group, target): re-inviting resets the existing row back
// to pending with fresh key material instead of stacking duplicates.
type GroupInvite struct {
	InviteID   uuid.UUID `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"invite_id"`
	GroupID    uuid.UUID `gorm:"type:uuid;not null;uniqueIndex:idx_group_invite_target" json:"group_id"`
	FromUser   uuid.UUID `gorm:"type:uuid;not null" json:"from_user"`
	ToUser     uuid.UUID `gorm:"type:uuid;not null;uniqueIndex:idx_group_invite_target" json:"to_user"`
	Status     string    `gorm:"type:varchar(16);not null;default:'pending'" json:"status"`
	WrappedKey string    `gorm:"type:text;not null" json:"wrapped_key"`
	KeyNonce   string    `gorm:"type:text;not null" json:"key_nonce"`
	CreatedAt  time.Time `gorm:"autoCreateTime" json:"created_at"`
}

// TableName overrides the default GORM table name for the GroupInvite model.
func (GroupInvite) TableName() string {
	return "group_invites"
}
